import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

export interface OrderItem {
  id: string;
  product_id: string;
  product_name_snapshot: string;
  product_image_snapshot: string | null;
  quantity: number;
  unit_price: number;
  total_price: number;
}

export interface Order {
  id: string;
  order_number: string;
  buyer_id: string;
  seller_id: string;
  status: string;
  subtotal: number;
  shipping_cost: number;
  tax_amount: number;
  commission_amount: number;
  total_amount: number;
  payment_method: string | null;
  payment_status: string;
  shipping_address_snapshot: Record<string, unknown> | null;
  notes: string | null;
  confirmed_at: string | null;
  shipped_at: string | null;
  delivered_at: string | null;
  completed_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
  order_items?: OrderItem[];
  // Joined profiles
  buyer?: { full_name: string | null; email: string | null } | null;
  seller?: { full_name: string | null; email: string | null } | null;
}

// ── Buyer's orders ──────────────────────────────────────────────
export function useBuyerOrders() {
  return useQuery<Order[]>({
    queryKey: ["buyer-orders"],
    queryFn: async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return [];

      const { data, error } = await supabase
        .from("orders")
        .select("*, order_items(*), seller:profiles!seller_id(full_name, email)")
        .eq("buyer_id", session.user.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return (data as unknown as Order[]) || [];
    },
  });
}

// ── Seller's orders ─────────────────────────────────────────────
export function useSellerOrders() {
  return useQuery<Order[]>({
    queryKey: ["seller-orders"],
    queryFn: async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return [];

      const { data, error } = await supabase
        .from("orders")
        .select("*, order_items(*), buyer:profiles!buyer_id(full_name, email)")
        .eq("seller_id", session.user.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return (data as unknown as Order[]) || [];
    },
  });
}

// ── Single order ────────────────────────────────────────────────
export function useOrder(id: string | undefined) {
  return useQuery<Order | null>({
    queryKey: ["order", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("orders")
        .select("*, order_items(*), buyer:profiles!buyer_id(full_name, email), seller:profiles!seller_id(full_name, email)")
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as unknown as Order;
    },
    enabled: !!id,
  });
}

// ── Create order from cart ──────────────────────────────────────
interface CreateOrderInput {
  shippingAddress: Record<string, unknown>;
  paymentMethod: string;
  notes?: string;
}

export function useCreateOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: CreateOrderInput) => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) throw new Error("Not authenticated");

      // 1. Fetch cart items with product details
      const { data: cartItems, error: cartError } = await supabase
        .from("cart_items")
        .select("*, products(id, name, images, min_price, unit, seller_id)")
        .eq("user_id", session.user.id);

      if (cartError) throw cartError;
      if (!cartItems || cartItems.length === 0) throw new Error("Cart is empty");

      // 2. Group cart items by seller
      const bySeller: Record<string, typeof cartItems> = {};
      for (const item of cartItems) {
        const sellerId = (item as unknown as { products: { seller_id: string } }).products.seller_id;
        if (!bySeller[sellerId]) bySeller[sellerId] = [];
        bySeller[sellerId].push(item);
      }

      const createdOrders: string[] = [];

      // 3. Create one order per seller
      for (const [sellerId, items] of Object.entries(bySeller)) {
        const subtotal = items.reduce((sum, item) => {
          const product = (item as unknown as { products: { min_price: number } }).products;
          return sum + product.min_price * item.quantity;
        }, 0);
        const shippingCost = 15000;
        const totalAmount = subtotal + shippingCost;

        // Insert order (order_number auto-generated by trigger)
        const { data: order, error: orderError } = await supabase
          .from("orders")
          .insert({
            order_number: "", // trigger will set
            buyer_id: session.user.id,
            seller_id: sellerId,
            status: "pending",
            subtotal,
            shipping_cost: shippingCost,
            total_amount: totalAmount,
            payment_method: input.paymentMethod,
            payment_status: "pending",
            shipping_address_snapshot: input.shippingAddress,
            notes: input.notes || null,
          })
          .select()
          .single();

        if (orderError) throw orderError;

        // Insert order items
        const orderItems = items.map(item => {
          const product = (item as unknown as { products: { id: string; name: string; images: string[]; min_price: number } }).products;
          return {
            order_id: order.id,
            product_id: product.id,
            product_name_snapshot: product.name,
            product_image_snapshot: product.images?.[0] || null,
            quantity: item.quantity,
            unit_price: product.min_price,
            total_price: product.min_price * item.quantity,
          };
        });

        const { error: itemsError } = await supabase
          .from("order_items")
          .insert(orderItems);

        if (itemsError) throw itemsError;
        createdOrders.push(order.id);
      }

      // 4. Clear cart
      await supabase
        .from("cart_items")
        .delete()
        .eq("user_id", session.user.id);

      return createdOrders;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["cart"] });
      queryClient.invalidateQueries({ queryKey: ["buyer-orders"] });
      queryClient.invalidateQueries({ queryKey: ["seller-orders"] });
    },
  });
}

// ── Update order status ─────────────────────────────────────────
export function useUpdateOrderStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ orderId, status }: { orderId: string; status: string }) => {
      const { error } = await supabase
        .from("orders")
        .update({ status })
        .eq("id", orderId);

      if (error) throw error;
    },
    onSuccess: (_data, variables) => {
      queryClient.invalidateQueries({ queryKey: ["buyer-orders"] });
      queryClient.invalidateQueries({ queryKey: ["seller-orders"] });
      queryClient.invalidateQueries({ queryKey: ["order", variables.orderId] });
    },
  });
}
