// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujhjroootvycgormsvhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqaGpyb29vdHZ5Y2dvcm1zdmhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NzE4OTUsImV4cCI6MjA5MDQ0Nzg5NX0.LVa0P_5lcuyJloyFFX9GqkHzJnVw1ATIBhCCDJ2k71Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});